
db:
- name: default
  ENGINE: django.db.backends.mysql
  DB_NAME: cmdb
  USER: root
  PASSWORD: bqjrcmdb
  HOST: 10.83.36.87
  PORT: 3306




other:
- name: parameters
  txt_base_dir: D:/scripts/scrapy/laijie/sucai/txts
